# Specify version format
version: "1.0.0.{build}"

# Image to use
image: Visual Studio 2017

# Branches to build
branches:
  only: 
    - master

# Clone depth
clone_depth: 1

# Including commits with 'build' comment
only_commits:
  message: build

# Cache files to speed up build
cache:
    - C:\mingw.7z -> .appveyor.yml
    - C:\ProgramData\chocolatey\bin -> .appveyor.yml
    - C:\ProgramData\chocolatey\lib -> .appveyor.yml
    - C:\ProgramData\chocolatey\cache -> .appveyor.yml

# Build matrix
environment:
  matrix:
    - type: MinGW
      build: call mingw.bat
      command: cmd /C
    - type: VisualStudio
      build: call vs.bat
      command: cmd /C

# Allow to fail on first error in matrix
matrix:
  fast_finish: true

# Scripts that run after cloning repository
install:
  # Doxygen
  - choco install --cache "C:\ProgramData\chocolatey\cache" --force doxygen.portable
  - choco install --cache "C:\ProgramData\chocolatey\cache" --force ghostscript
  - choco install --cache "C:\ProgramData\chocolatey\cache" --force graphviz
  - choco install --cache "C:\ProgramData\chocolatey\cache" --force miktex
  # MinGW
  - if "%type%"=="MinGW" if not exist "C:\mingw.7z" appveyor-retry appveyor DownloadFile "http://downloads.sourceforge.net/mingw-w64/x86_64-6.3.0-release-posix-seh-rt_v5-rev1.7z" -FileName "C:\mingw.7z"
  - if "%type%"=="MinGW" 7z x -y -oC:\ "C:\mingw.7z" > nul
  - if "%type%"=="MinGW" set PATH=C:\mingw64\bin;%PATH:C:\Program Files\Git\usr\bin;=%
  - if "%type%"=="MinGW" set INCLUDE=C:\mingw64\x86_64-w64-mingw32\include;%INCLUDE%
  - if "%type%"=="MinGW" copy /Y "modules\websocketpp.patch" "C:\mingw64\lib\gcc\x86_64-w64-mingw32\6.3.0\include\c++\x86_64-w64-mingw32\bits\error_constants.h"
  # Visual Studio
  - if "%type%"=="VisualStudio" set PATH=C:\Program Files\MiKTeX 2.9\miktex\bin\x64;C:\Program Files\gs\gs9.21\bin;%PATH%
  - if "%type%"=="VisualStudio" set INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um;%INCLUDE%
  - if "%type%"=="VisualStudio" set LIB=C:\Program Files (x86)\Windows Kits\10\Lib\10.0.15063.0\um\x64;%LIB%
  - if "%type%"=="VisualStudio" copy "C:\Program Files\gs\gs9.21\bin\gswin64c.exe" "C:\Program Files\gs\gs9.21\bin\gswin32c.exe"
  # git
  - '%command% "cmake --version"'
  - '%command% "git config --global user.name "AppVeyor""'
  - '%command% "git config --global user.email "team@appveyor.com""'
  - '%command% "git config --global push.default simple"'
  - git submodule update --init --recursive --remote

# Build scripts
build_script:
  - cd build
  - '%build%'

# Test scripts
test: off
